name: Jekyll CI-CD

on:
  push:
    branches: [ webp ]

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: update apt-get
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo -E apt-get update -qq -o Acquire::Retries=3
      - name: install snapd
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo -E apt-get install --fix-missing -qq -o Acquire::Retries=3
          snapd
      - name: install libvips
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo -E snap install libvips -qq -o Acquire::Retries=3
      - name: ðŸ’¾ checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - name: ðŸš€ enable cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os}}-gem-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Specify the target branch (optional)
      - name: ðŸ›  build & deploy
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'test-pages'