name: Jekyll CI-CD

on:
  push:
    branches: [ webp ]

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ’¾ checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - name: ðŸš€ enable cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os}}-gem-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # Specify the target branch (optional)
      - name: ðŸ›  build & deploy
        uses: helaili/jekyll-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'test-pages'
          pre_build_commands:
            apk --update add vips vips-tools